<a href="https://colab.research.google.com/github/Ankur099IIT/Natural-Language-Processing-Course-3-Deeplearning.ai/blob/main/Generating_Sequences_and_Padding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = ['My name is Ankur Tiwari',
             'I love to learn new things everyday',
             'Watching space documentaries ia my favourite pass time',
             'I am enjoying learning tensorflow, pandas, numpy, matplotlib.']

tokenizer = Tokenizer(num_words = 100, oov_token = '<OOV>')

tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index

sequence = tokenizer.texts_to_sequences(sentences)

print(word_index)
print(sequence)





{'<OOV>': 1, 'my': 2, 'i': 3, 'name': 4, 'is': 5, 'ankur': 6, 'tiwari': 7, 'love': 8, 'to': 9, 'learn': 10, 'new': 11, 'things': 12, 'everyday': 13, 'watching': 14, 'space': 15, 'documentaries': 16, 'ia': 17, 'favourite': 18, 'pass': 19, 'time': 20, 'am': 21, 'enjoying': 22, 'learning': 23, 'tensorflow': 24, 'pandas': 25, 'numpy': 26, 'matplotlib': 27}
[[2, 4, 5, 6, 7], [3, 8, 9, 10, 11, 12, 13], [14, 15, 16, 17, 2, 18, 19, 20], [3, 21, 22, 23, 24, 25, 26, 27]]


In [10]:
# Padding

padded = pad_sequences(sequence, padding = 'post', maxlen = 10)

print('\nPadded Sequence:')
print(padded)


Padded Sequence:
[[ 2  4  5  6  7  0  0  0  0  0]
 [ 3  8  9 10 11 12 13  0  0  0]
 [14 15 16 17  2 18 19 20  0  0]
 [ 3 21 22 23 24 25 26 27  0  0]]


In [14]:
# Out-of-vocabulary token

test_data = ['Practice makes a man perfect',
             'if in doubt run the code',
             'ML practitioner moto- Experiment, Experiment, Experiment',
             'Ankur loves dogs']

test_seq = tokenizer.texts_to_sequences(test_data)

print('\n Word index',word_index)
print('\nTest Sequence', test_seq)


 Word index {'<OOV>': 1, 'my': 2, 'i': 3, 'name': 4, 'is': 5, 'ankur': 6, 'tiwari': 7, 'love': 8, 'to': 9, 'learn': 10, 'new': 11, 'things': 12, 'everyday': 13, 'watching': 14, 'space': 15, 'documentaries': 16, 'ia': 17, 'favourite': 18, 'pass': 19, 'time': 20, 'am': 21, 'enjoying': 22, 'learning': 23, 'tensorflow': 24, 'pandas': 25, 'numpy': 26, 'matplotlib': 27}

Test Sequence [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [6, 1, 1]]


In [19]:
padded = pad_sequences(test_seq, padding = 'post', maxlen = 10)

print('\n Padded Sequences:')
print(padded) # here token 1 represent the 'OOV'(words that are not found in sentences) and only keyword "Ankur" with index 6 is common


 Padded Sequences:
[[1 1 1 1 1 0 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [6 1 1 0 0 0 0 0 0 0]]
